# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfermedad',
            old_name='serie',
            new_name='cie10',
        ),
    ]
