# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendacion', '0002_auto_20170424_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='cie10',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
