# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendacion', '0003_auto_20170424_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
