# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendacion', '0004_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pariente',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('a', 'Agendador'), ('m', 'Medico'), ('s', 'Administrador')], max_length=1),
        ),
    ]
